# Generated by Django 5.2.1 on 2026-06-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0004_worklog_timesheet_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='worklog',
            name='work_log_work_it_c29d0f_idx',
        ),
    ]
