# Generated by Django 6.0.5 on 2026-06-17 08:57

import django.db.models.deletion
import packages.workflow.field
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followups', '0001_initial'),
        ('pmt_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='workflow_state',
            field=packages.workflow.field.StateField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='pmt_workflow.state'),
        ),
    ]
